services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Document/'
            - '../src/Kernel.php'

    App\Security\InputSanitizer:
        public: false
